import './globals.css';
import Navbar from '../components/Navbar/index';
import Footer from '..//components/Footer/Footer';
import Providers from "./providers";

export const metadata = {
  title: 'DialBackup',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Arial' }}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
