import './globals.css';
import Navbar from '../components/Navbar/index';
import Footer from '..//components/Footer/Footer';


export const metadata = {
  title: '1-800 BackupCall',
  description: 'Generated by create next app',
 }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Arial' }}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
